### ISSUE TITLE
Update Register Form

### ISSUE THREAD

**Issue by DanielOhrin** [DanielOhrin/NutriHelp#4]
When a new user registers for NutriHelp, we need a lot more data than just their email/pw.

Data required *FROM USER*:
- Email
- Password
_The above info is all that is required for firebase. However, you should disable the submit button until all fields are filled out._
- UserName
- FirstName
- LastName
- Gender ("M" or "F")
- BirthDate
- Weight (in kg)
- Height (in cm)
- ActivityLevel (1.2, 1.3, 1.4) -- Sedentary | Light/Average Exercise | Intense/Above average exercise
- WeightGoal (1, 2, 3, 4, 5) --- 1. Lose 2lb/week   2. Lose 1/week  3. Maintain weight   4. Gain 1/week   5. Gain 2/week

For this ticket, also implement a controller action for saving the user's data.
Make sure to include DateCreated.

**Comment by KaptainCS3** [comment]
!assign

**Comment by KaptainCS3** [comment]
design template needed

**Comment by DanielOhrin** [comment]
#9 closes this
